apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

bases:
  - argocd/base

resources:
  - managed-cert-argocd.yaml
  - service.yaml
  - ingress.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    path: argocd-server-insecure-patch.yaml
