apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project
  # Source of the application manifests
  source:
    # FIX ME
    repoURL: "git@github.com:Luxas98/terraform-gcp-argocd.git"
    path: argcd-apps/redis/base
    # Branch name
    targetRevision: master
  # Destination cluster and namespace to deploy the application
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true
  # Ignore differences at the specified json pointers
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec
