apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: default-

bases:
  - ../../base

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      # FIX ME
      name: project
    path: ./server-patch.yaml
