apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  # https://argoproj.github.io/argo-cd/operator-manual/rbac/
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-rbac-cm.yaml#L26
  policy.default: role:admin
